language: node_js
node_js:
  - node
cache:
  - npm
  - yarn
script:
  - yarn lint
  - yarn typecheck
  - yarn test:ci
deploy:
  skip_cleanup: true
  provider: npm
  email: d34thwings@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: D34THWINGS/react-named-router
