version: 2.1

orbs:
  node: circleci/node@0.0.9

jobs:
  install:
    executor:
      name: node/node
      tag: '11'
    working_directory: ~/react-named-router
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
          cache-key: yarn.lock
      - persist_to_workspace:
          root: ~/
          paths:
            - react-named-router

  build:
    executor:
      name: node/node
      tag: '11'
    working_directory: ~/react-named-router
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn build
      - store_artifacts:
          path: ~/react-named-router/es6
      - store_artifacts:
          path: ~/react-named-router/lib
      - persist_to_workspace:
          root: ~/
          paths:
            - react-named-router

  test:
    executor:
      name: node/node
      tag: '11'
    working_directory: ~/react-named-router
    environment:
      JEST_JUNIT_OUTPUT: "reports/jest/unit-test-results.xml"
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
      - run:
          command: yarn typecheck
          when: always
      - run:
          command: yarn test:ci
          when: always
      - store_test_results:
          path: reports/

workflows:
  version: 2
  main_workflow:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - build:
          requires:
            - install
      - test:
          requires:
            - install
